name: 'calculator'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Will Streuli <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  polymer: '^1.0.0-rc.17'
  polymer_elements: '^1.0.0-rc.8'
  web_components: '^0.12.0'


transformers:
- dart_to_js_script_rewriter
- polymer:
    entry_points: web/index.html
